### ISSUE TITLE
ng-model set to undefined when submitting a form

### ISSUE THREAD

**Issue by Kitcat711** [jstroem/ng-input-currency#2]
Using angular 1.5.3
When using the input ng-currency-input in a form, when the button initiating the ng-submit, the ng-model is set to undefined.
How can I fix that?

**Comment by jstroem** [comment]
Hi @Kitcat711,

Can you make a simple example with the problem? Would make it easier for me to help you.

**Comment by HarpoMarx69** [comment]
Have the same issue in my project. Here a plunkr: https://plnkr.co/edit/C22mY69DarflscYtRiL5?p=preview

**Comment by Kitcat711** [comment]
Hi jstroem, 
I finally gave up and I am using a different solution through ng-currency which worked fine.
Just wanted to let you know: to be polite is a must.

Kitcat

**Comment by SapioBeasley** [comment]
Still applies, just ran into this issue as well ...

**Comment by a-stankevich** [comment]
@Kitcat711 I'm having the same issue (and some more). Can you share what solution do you use?
