### ISSUE TITLE
Cannot read property 'createChild' of null

### ISSUE THREAD

**Issue by alanssoares** [jstroem/ng-input-currency#6]
I'm using a simple input like this: 

`<input type="text" ng-input-currency ng-model="balance">`

Then the error occur because the options is undefined and the condition expect null, so you need add the undefined comparator to solve this problem.
 
....  

var opts = {
    updateOn: 'blur enter',
    updateOnDefault: false
  };
  if ($ngModel.options !== null)
    opts = $ngModel.$options.createChild(opts);

.....

**Comment by jstroem** [comment]
New version with fix has been created.
