### ISSUE TITLE
Is not a module

### ISSUE THREAD

**Issue by pmcavoy89** [jstroem/ng-input-currency#7]
I'm not getting a module and so I had to change the `package.json` to use the Javascript file from the `src` directory to get it to work. Not sure what's going wrong here.

**Comment by jstroem** [comment]
What setup do you run with and do you some sort of stack trace?

**Comment by pmcavoy89** [comment]
When I `console.log()`, after importing the module into a file in my project, it is `undefined`. This is when I don't modify the `package.json` of the project. 

When you ask, what setup do I run? Are you asking how I installed the module? Or are you saying what is my start command? I'll have to get back to you on getting a stack trace.

**Comment by jstroem** [comment]
This should be fixed with latest version @pmcavoy89 can you confirm?

**Comment by jstroem** [comment]
fixed?
